// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS87v4FtfEN-ZBCpsABSti77RpEo2ADgI',
    appId: '1:1087007365730:web:9fd55886ffa5317c240f3b',
    messagingSenderId: '1087007365730',
    projectId: 'ase-456-team-project',
    authDomain: 'ase-456-team-project.firebaseapp.com',
    storageBucket: 'ase-456-team-project.firebasestorage.app',
    measurementId: 'G-2SX377E8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-a3fCww2BX1GrUuWM8w67oIKcI-MWqho',
    appId: '1:1087007365730:android:6f4e64c25b4edbd6240f3b',
    messagingSenderId: '1087007365730',
    projectId: 'ase-456-team-project',
    storageBucket: 'ase-456-team-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQ2qUDOAoy7RQoyPNuuTuBvOQRbddsIE',
    appId: '1:1087007365730:ios:938b8bcff1ec279a240f3b',
    messagingSenderId: '1087007365730',
    projectId: 'ase-456-team-project',
    storageBucket: 'ase-456-team-project.firebasestorage.app',
    iosBundleId: 'com.example.p5Expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQ2qUDOAoy7RQoyPNuuTuBvOQRbddsIE',
    appId: '1:1087007365730:ios:938b8bcff1ec279a240f3b',
    messagingSenderId: '1087007365730',
    projectId: 'ase-456-team-project',
    storageBucket: 'ase-456-team-project.firebasestorage.app',
    iosBundleId: 'com.example.p5Expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS87v4FtfEN-ZBCpsABSti77RpEo2ADgI',
    appId: '1:1087007365730:web:1c2a2b8e1dd42312240f3b',
    messagingSenderId: '1087007365730',
    projectId: 'ase-456-team-project',
    authDomain: 'ase-456-team-project.firebaseapp.com',
    storageBucket: 'ase-456-team-project.firebasestorage.app',
    measurementId: 'G-VDBB207B5L',
  );
}
